project:
  type: website

format:
  html:
    theme: darkly     # dark theme of your choice
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - section: "ğŸ  Home"
        contents:
          - index.ipynb
      - section: "ğŸ§  Transformers"
        contents:
          - 01_LLMForwardPass.ipynb
          - 05_GPTDecoder.ipynb
          - 06_MultiModal.ipynb
      - section: "ğŸ”§ Fine-Tuning"
        contents:
          - 02_LoRAPytorch.ipynb
          - 03_DAFTSFT.ipynb
          - 07_DistilationWeightInit.ipynb
      - section: "ğŸ¤– Agents"
        contents:
          - 08_AgentFromFirstPrinciple.ipynb
          - 09_KhazadDum.ipynb
      - section: "ğŸ“š Fundamentals"
        contents:
          - 04_PythonWalkThrough.ipynb
          - 10_BenchmarkingTOkenizer4Odia.ipynb

metadata-files: [nbdev.yml]